using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace CodeObfuscation
{
    class MXDLWWEMLDAEJGXLOIJDKSNHHDVMQFTNKPWPLWSMXHAKLFQBJXUORJHRKTDTBQTFIKSRHHAQNVEDRCTB: CSharpSyntaxRewriter
    {
        public MXDLWWEMLDAEJGXLOIJDKSNHHDVMQFTNKPWPLWSMXHAKLFQBJXUORJHRKTDTBQTFIKSRHHAQNVEDRCTB() { }

        public override SyntaxNode VisitClassDeclaration(ClassDeclarationSyntax node)
        {
            String LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD= node.Identifier.ValueText;
            String PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS= "";
            if (IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX.ContainsKey(LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD))
            {
                PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS = IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX[LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD];
            }
            else
            {
                PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS = IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.REEEMFRGJWOQFADSSPEMXUQJWAMNRLFEWRJILXMKVFIKDOBESRBESNUVMSGMQENV(IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX.Count() + 1);
                IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX[LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD] = PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS;
            }

            ClassDeclarationSyntax KTCRJETBIEFPTXLHLSCALWRBWEBUFEAHXBIFNCUDPRJDCIUNKUQWATOMBBSFDXUDDVPSPFRIWWJRMOWOH= node.WithIdentifier(Identifier(PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS)).WithLeadingTrivia(node.GetLeadingTrivia()).WithTrailingTrivia(node.GetTrailingTrivia());
            return node.ReplaceNode(node, KTCRJETBIEFPTXLHLSCALWRBWEBUFEAHXBIFNCUDPRJDCIUNKUQWATOMBBSFDXUDDVPSPFRIWWJRMOWOH);
        }

    }
}
