using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace CodeObfuscation
{
    class TGORVOQUFOGUAEAOLRPDDRNDFCFAGJLIVQKROMJIIJLSJOCGMNCXLBECRKMTJPNTCVXHRGXXHHT: CSharpSyntaxRewriter
    {
        public TGORVOQUFOGUAEAOLRPDDRNDFCFAGJLIVQKROMJIIJLSJOCGMNCXLBECRKMTJPNTCVXHRGXXHHT() { }

        public override SyntaxNode VisitClassDeclaration(ClassDeclarationSyntax node)
        {
            String QRIDANWXOXHXQGLUOCDMOBMVISMDOVCCPBHHVMDSWCLMJQLTEHXESQWOEKTGATJQVEI= node.Identifier.ValueText;
            String OPKFGNUDIKDULAHRRIQFEJJDGGHESRWBKXURAODJJVSQFPNLXELBAGXFFHWAFQIPLCKMEOQDEH= "";
            if (CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB.Instance.EFPPBVBEPWQUAUDRHGWSMXHHEALKSSSLSUKHIWKDSAARQQHGGDWDEKTEVILAKO.ContainsKey(QRIDANWXOXHXQGLUOCDMOBMVISMDOVCCPBHHVMDSWCLMJQLTEHXESQWOEKTGATJQVEI))
            {
                OPKFGNUDIKDULAHRRIQFEJJDGGHESRWBKXURAODJJVSQFPNLXELBAGXFFHWAFQIPLCKMEOQDEH = CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB.Instance.EFPPBVBEPWQUAUDRHGWSMXHHEALKSSSLSUKHIWKDSAARQQHGGDWDEKTEVILAKO[QRIDANWXOXHXQGLUOCDMOBMVISMDOVCCPBHHVMDSWCLMJQLTEHXESQWOEKTGATJQVEI];
            }
            else
            {
                OPKFGNUDIKDULAHRRIQFEJJDGGHESRWBKXURAODJJVSQFPNLXELBAGXFFHWAFQIPLCKMEOQDEH = CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB.Instance.ATIFULKWNSMBPDJXAPMKQITEVGMJGBCKCXAQDBWBAVKUHIIWWHQBLJJPXEH(CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB.Instance.EFPPBVBEPWQUAUDRHGWSMXHHEALKSSSLSUKHIWKDSAARQQHGGDWDEKTEVILAKO.Count() + 1);
                CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB.Instance.EFPPBVBEPWQUAUDRHGWSMXHHEALKSSSLSUKHIWKDSAARQQHGGDWDEKTEVILAKO[QRIDANWXOXHXQGLUOCDMOBMVISMDOVCCPBHHVMDSWCLMJQLTEHXESQWOEKTGATJQVEI] = OPKFGNUDIKDULAHRRIQFEJJDGGHESRWBKXURAODJJVSQFPNLXELBAGXFFHWAFQIPLCKMEOQDEH;
            }

            ClassDeclarationSyntax RFSSOXWMRGLVUMIAEAOWQUPPLPSMFNDQDGLUWQVTLDUNPACTJGTWRJCUOCHXFJGDDTROAMBLDSLN= node.WithIdentifier(Identifier(OPKFGNUDIKDULAHRRIQFEJJDGGHESRWBKXURAODJJVSQFPNLXELBAGXFFHWAFQIPLCKMEOQDEH)).WithLeadingTrivia(node.GetLeadingTrivia()).WithTrailingTrivia(node.GetTrailingTrivia());
            return node.ReplaceNode(node, RFSSOXWMRGLVUMIAEAOWQUPPLPSMFNDQDGLUWQVTLDUNPACTJGTWRJCUOCHXFJGDDTROAMBLDSLN);
        }

    }
}
