using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Symbols;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.IO;

namespace CodeObfuscation
{
    class SLPQFPNVXWLMISQGLMX    {
        public SLPQFPNVXWLMISQGLMX() { }

        public void RPGHNEFRFOLWEBMDQWNQ(EMKKIQGAFSPEPJOFPKBDWLBAMLWAFLGKPBNOLCELEDMTGSXCHCUJSVIRLJWUSGTRMENNUXRNFNWSXFRRMUQC.En_Priority[] prioritiesTablo) 
        {
            Tuple<Compilation, int> SVFSESQ= DGOETNGLJTLSLVLSLDBLA();

            for (int KUBTIVCJ= 0; KUBTIVCJ < SVFSESQ.Item2; KUBTIVCJ++)
            {
                foreach (SyntaxTree sourceTree in SVFSESQ.Item1.SyntaxTrees)
                {
                    MXDLWWEMLDAEJGXLOIJDKSNHHDVMQFTNKPWPLWSMXHAKLFQBJXUORJHRKTDTBQTFIKSRHHAQNVEDRCTB IKNSQVEFN= new MXDLWWEMLDAEJGXLOIJDKSNHHDVMQFTNKPWPLWSMXHAKLFQBJXUORJHRKTDTBQTFIKSRHHAQNVEDRCTB();
                    SyntaxNode PLVISRLQPT= IKNSQVEFN.Visit(sourceTree.GetRoot());
                    LKIMCHEKUDLIPXPVFXFRCWECHXBJUXLDEVQNLPBOLHTCGAHXSUHPRVEMFFECFTNUQIERHBJOVOFTDBUHQC EQBSLINEJGI= new LKIMCHEKUDLIPXPVFXFRCWECHXBJUXLDEVQNLPBOLHTCGAHXSUHPRVEMFFECFTNUQIERHBJOVOFTDBUHQC();
                    SyntaxNode GIEKDEVPSLOQ= EQBSLINEJGI.Visit(PLVISRLQPT);
                    OXNWONKBDPOQUAUXOFUANWIXHNQCTWLUKXDUQMXPFJMFIARLWUWDFRPPOOPAVIGFDSFVUXGBGFT PCQUIQDOCRBWR= new OXNWONKBDPOQUAUXOFUANWIXHNQCTWLUKXDUQMXPFJMFIARLWUWDFRPPOOPAVIGFDSFVUXGBGFT();
                    SyntaxNode HPBJCQTWFIDRVO= PCQUIQDOCRBWR.Visit(GIEKDEVPSLOQ);
                    OAQTJHRDHGKWIPRWKVUOPQLQRCPJJDIVKDENEUWUXDSCEWGOBEPWLCKWNXBHPISDVMMELDROWXOLWIMTUAH MOBUHNXJPSMEMFQ= new OAQTJHRDHGKWIPRWKVUOPQLQRCPJJDIVKDENEUWUXDSCEWGOBEPWLCKWNXBHPISDVMMELDROWXOLWIMTUAH();
                    SyntaxNode GNHFRUMTFQTTRKSN= MOBUHNXJPSMEMFQ.Visit(HPBJCQTWFIDRVO);
                    JGTTCXVXIRQKIXLUXARCAVDLRVVEUFPOEERSUBJXEKQDUHOPEFXJWIKMCHBFCQDDCCFDGQ CKBOXAVRIRVAGVVDN= new JGTTCXVXIRQKIXLUXARCAVDLRVVEUFPOEERSUBJXEKQDUHOPEFXJWIKMCHBFCQDDCCFDGQ();
                    SyntaxNode GWTTLESATTEMRFXUFJ= CKBOXAVRIRVAGVVDN.Visit(GNHFRUMTFQTTRKSN);
                    /*if (occurenceRewritedNode != sourceTree.GetRoot())
                    {
                        File.WriteAllText(sourceTree.FilePath, occurenceRewritedNode.ToFullString());
                    }*/
                    //save without condition
                    File.WriteAllText(sourceTree.FilePath, GWTTLESATTEMRFXUFJ.ToFullString());
                }
            }
        }
        public Tuple<Compilation, int> DGOETNGLJTLSLVLSLDBLA()
        {

            String WIGMAHKTOXIWTTLABLAVRH= @"..\..\Program.cs";
            String JDRKGNSPMUBQFWHPSGTPTUC= @"..\..\ProgramOBF.cs";
            String TPCARKPBNGOXDTOAVBWLLUDO= File.ReadAllText(WIGMAHKTOXIWTTLABLAVRH);
            SyntaxTree NRJRRBCMNAVTEMAFUTMJOXEUE=
                           CSharpSyntaxTree.ParseText(TPCARKPBNGOXDTOAVBWLLUDO)
                                           .WithFilePath(JDRKGNSPMUBQFWHPSGTPTUC);

            String FWOUJPXLLLAAWHLECJCVTUIARO= @"..\..\CompilationManager.cs";
            String QISXOMNMMDLPEJWHQBAFWLAFMNB= @"..\..\CompilationManagerOBF.cs";
            String WJIONDSWPRLVLKJSIQKFRXLDGALQ= File.ReadAllText(FWOUJPXLLLAAWHLECJCVTUIARO);
            SyntaxTree FHNLBKODDMVMJKGNEEMSMQPMBHIXV=
                           CSharpSyntaxTree.ParseText(WJIONDSWPRLVLKJSIQKFRXLDGALQ)
                                           .WithFilePath(QISXOMNMMDLPEJWHQBAFWLAFMNB);

            String FHNQCRHEAUBUGPTSWUGQWWCMQEMQAK= @"..\..\SharedContainer.cs";
            String RCOGWEIUGQXIEIKWFBTRCKBGWGFAXWF= @"..\..\SharedContainerOBF.cs";
            String OEOCXFAQPJCNNQOSSBSWKUHHGAIHQXIU= File.ReadAllText(FHNQCRHEAUBUGPTSWUGQWWCMQEMQAK);
            SyntaxTree ILIEOFLQFJEHAVLNILLXFASSUHTWVQXPB=
                           CSharpSyntaxTree.ParseText(OEOCXFAQPJCNNQOSSBSWKUHHGAIHQXIU)
                                           .WithFilePath(RCOGWEIUGQXIEIKWFBTRCKBGWGFAXWF);

            String FECIJEMNBQBPXGJMSWFLIPIROHHJNTNJMF= @"..\..\OccurrenceRewriter.cs";
            String SQJFXHWJDHQCVAKJDSSEROUJRCUCAGDPDRM= @"..\..\OccurrenceRewriterOBF.cs";
            String QDMXVNXLAALKHXDQTPIMDUXLUKUJVEAXDMRF= File.ReadAllText(FECIJEMNBQBPXGJMSWFLIPIROHHJNTNJMF);
            SyntaxTree OSUPSDTJFPNCUOIASFIUDACKQNNTXMGSGVBAS=
                           CSharpSyntaxTree.ParseText(QDMXVNXLAALKHXDQTPIMDUXLUKUJVEAXDMRF)
                                           .WithFilePath(SQJFXHWJDHQCVAKJDSSEROUJRCUCAGDPDRM);

            String RSAAOGFVRMHUAEVDUCNPJWEOXJRJSUXMHGBKIU= @"..\..\MethodRewriter.cs";
            String MSVNXBFXXIIPJTLIITOJAFMUCUNTNSDLSANTSUW= @"..\..\MethodRewriterOBF.cs";
            String CIAKJADKDAWVGUWTHGBLCMKKFEVUJGQOMULBATDT= File.ReadAllText(RSAAOGFVRMHUAEVDUCNPJWEOXJRJSUXMHGBKIU);
            SyntaxTree WKJSOUUOUEFNQITOVNFECHAUIHJJIUTMCFMQCQUII=
                           CSharpSyntaxTree.ParseText(CIAKJADKDAWVGUWTHGBLCMKKFEVUJGQOMULBATDT)
                                           .WithFilePath(MSVNXBFXXIIPJTLIITOJAFMUCUNTNSDLSANTSUW);

            String HAFADWDAVEKNWRPJMJGLKFXIRKKUDMERUUSGTTFJFJ= @"..\..\ClassRewriter.cs";
            String LQJWDMUGNGNVVBAUHQLHUJXQRCWIOQEVFBRGXSGWXUW= @"..\..\ClassRewriterOBF.cs";
            String WEWXRGWMMVWMCRQEBNLQUCQQTIRVNJNHAKBLTDFCQEPX= File.ReadAllText(HAFADWDAVEKNWRPJMJGLKFXIRKKUDMERUUSGTTFJFJ);
            SyntaxTree GMONGNFJLECTMFDIMBWCIPMQPEJVHJAPKQKGRDOXEDTUH=
                           CSharpSyntaxTree.ParseText(WEWXRGWMMVWMCRQEBNLQUCQQTIRVNJNHAKBLTDFCQEPX)
                                           .WithFilePath(LQJWDMUGNGNVVBAUHQLHUJXQRCWIOQEVFBRGXSGWXUW);

            String FXNAUNPGMPOAWWCEHCCDKJUTUPJKWWETPIKFTVKTJJVBTG= @"..\..\ConstructorRewriter.cs";
            String SFMTVBRQVTDSDFEEHOKTINLUIJPGSBLSXOUDWDADBXLOBBS= @"..\..\ConstructorRewriterOBF.cs";
            String FOFBGOAVERPKMKKVTIISNIBFENHRJCVSHOJPNAEEXQQKHQMQ= File.ReadAllText(FXNAUNPGMPOAWWCEHCCDKJUTUPJKWWETPIKFTVKTJJVBTG);
            SyntaxTree OBQGRGEVNXUQGGLCTUDVASISDDTUQOWLBOCIKPBBKMCNDLVRF=
                           CSharpSyntaxTree.ParseText(FOFBGOAVERPKMKKVTIISNIBFENHRJCVSHOJPNAEEXQQKHQMQ)
                                           .WithFilePath(SFMTVBRQVTDSDFEEHOKTINLUIJPGSBLSXOUDWDADBXLOBBS);

            String NOKNPQTQVCNKIFWBIPQDCQETBKLQSPPGCPCALWJWGPMMLOBHDM= @"..\..\VariableRewriter.cs";
            String SUFNCVKOLEEDWGLHIQCWNKGSUKDPIKIEMFUTAMNFOVLERDRGBDG= @"..\..\VariableRewriterOBF.cs";
            String JEFWINLRPRSFATXOQJQGTDVHQWBAQRVOEEXAGHMFNTVLTPKIRMBV= File.ReadAllText(NOKNPQTQVCNKIFWBIPQDCQETBKLQSPPGCPCALWJWGPMMLOBHDM);
            SyntaxTree JVLGGWGJMKAVUEBUUWHJUKRXFJLAMQGEQXEHQRRIBDRCTAPPOOMTE=
                           CSharpSyntaxTree.ParseText(JEFWINLRPRSFATXOQJQGTDVHQWBAQRVOEEXAGHMFNTVLTPKIRMBV)
                                           .WithFilePath(SUFNCVKOLEEDWGLHIQCWNKGSUKDPIKIEMFUTAMNFOVLERDRGBDG);

            String QAWDLAVKFVTETFUXRDCFXIRRPEFSUKWDLXAXGEFQUWTFVWXSSQUKKN= @"..\..\Priority.cs";
            String FIGFMHTCNTXPQUFURNWJIAMMUQEKXEOMRVRQRBPVVRIAGFFDNVXGLAF= @"..\..\PriorityOBF.cs";
            String ETRITCIDJFLWTCNDPVAMOQMFOLBVBFHAQQMUXQUTMOWTTHKAASHJKMOM= File.ReadAllText(QAWDLAVKFVTETFUXRDCFXIRRPEFSUKWDLXAXGEFQUWTFVWXSSQUKKN);
            SyntaxTree HMSIBLBEVKFCNQDXBFXARQJHAAVHVWOEBANLWMSBNSVJBHLHPIHFNOTOC=
                           CSharpSyntaxTree.ParseText(ETRITCIDJFLWTCNDPVAMOQMFOLBVBFHAQQMUXQUTMOWTTHKAASHJKMOM)
                                           .WithFilePath(FIGFMHTCNTXPQUFURNWJIAMMUQEKXEOMRVRQRBPVVRIAGFFDNVXGLAF);

            SyntaxTree[] KHAOSGXUBBNCQANLWKXTAGRNNQNOJOLEXJMERKTLVNXGVEXHSSPDUSBDNK= {NRJRRBCMNAVTEMAFUTMJOXEUE, FHNLBKODDMVMJKGNEEMSMQPMBHIXV, ILIEOFLQFJEHAVLNILLXFASSUHTWVQXPB, OSUPSDTJFPNCUOIASFIUDACKQNNTXMGSGVBAS, WKJSOUUOUEFNQITOVNFECHAUIHJJIUTMCFMQCQUII, GMONGNFJLECTMFDIMBWCIPMQPEJVHJAPKQKGRDOXEDTUH, OBQGRGEVNXUQGGLCTUDVASISDDTUQOWLBOCIKPBBKMCNDLVRF, JVLGGWGJMKAVUEBUUWHJUKRXFJLAMQGEQXEHQRRIBDRCTAPPOOMTE, HMSIBLBEVKFCNQDXBFXARQJHAAVHVWOEBANLWMSBNSVJBHLHPIHFNOTOC};

            MetadataReference BBRJKKNIDGMIRLPLVLGKPIQGUOXHIEHIPGJRRMCNQNBQSJBDMIUOVDTQJKM=
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location);
            MetadataReference UKGAXXERKCWSJIRSCHALKNUTAIQKMLQIHXGCKNBQOQOBNOLFEIRIIXCGOKXO=
                    MetadataReference.CreateFromFile(typeof(SyntaxTree).Assembly.Location);
            MetadataReference GRFWJNKKCOHMFIVSWTFKVLGDSHAIVALXNKJVLQPXDACNBEDABIHTFNRTKBEBN=
                   MetadataReference.CreateFromFile(typeof(CSharpSyntaxTree).Assembly.Location);
            MetadataReference[] CMCCHXSWAGGDFGUIQBOEXGNQQSXQOKJMOKALALREIBBBAPXGVLSXNVNUXJKNXB= { BBRJKKNIDGMIRLPLVLGKPIQGUOXHIEHIPGJRRMCNQNBQSJBDMIUOVDTQJKM, UKGAXXERKCWSJIRSCHALKNUTAIQKMLQIHXGCKNBQOQOBNOLFEIRIIXCGOKXO, GRFWJNKKCOHMFIVSWTFKVLGDSHAIVALXNKJVLQPXDACNBEDABIHTFNRTKBEBN };

            return Tuple.Create(CSharpCompilation.Create("CodeObfuscation",
                                            KHAOSGXUBBNCQANLWKXTAGRNNQNOJOLEXJMERKTLVNXGVEXHSSPDUSBDNK,
                                            CMCCHXSWAGGDFGUIQBOEXGNQQSXQOKJMOKALALREIBBBAPXGVLSXNVNUXJKNXB,
                                            new CSharpCompilationOptions(
                                                    OutputKind.ConsoleApplication)) as Compilation, KHAOSGXUBBNCQANLWKXTAGRNNQNOJOLEXJMERKTLVNXGVEXHSSPDUSBDNK.Count());
        }
    }
}
