using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace CodeObfuscation
{
    class CPTGRCFGVRKTXDLVHQCNBIIENVVEWBAOQVTMQCASGWUVCLTRIIKGXBORHOQUFAITRUCC: CSharpSyntaxRewriter
    {
        private string IWEFQIHCMLBCCEUNPRPOHCFCKENFOADGJQIKEFOOSLEUNOSBETEAFLTGRCTMTBMLHTRJT= "override";
        private string KIJCAUTVIMTKMBTUDAVVCQCKCTQXRNRVIFSKSVFPXIINXCHAQPDTTLQRGWAFETETTWBGGI= "Main";

        public CPTGRCFGVRKTXDLVHQCNBIIENVVEWBAOQVTMQCASGWUVCLTRIIKGXBORHOQUFAITRUCC() { }

        public override SyntaxNode VisitMethodDeclaration(MethodDeclarationSyntax node)
        {
            String DTJAQTQNMGLGLQBHCOUHJFTKRWGQQBSUVRVXJOHHHVPHTKVHNCBAIXAVXWGRMXVLL= node.Identifier.ValueText;
            Boolean BFTGVRIMLXMPHCJWBVNBDUVAKEEMSAAASINWANNWIRLARNMCKUVDRFEFISTRNTSKWLVWMLW= false;
            foreach (SyntaxToken modifier in node.Modifiers)
            {
                if (modifier.ValueText.Equals(IWEFQIHCMLBCCEUNPRPOHCFCKENFOADGJQIKEFOOSLEUNOSBETEAFLTGRCTMTBMLHTRJT))
                {
                    BFTGVRIMLXMPHCJWBVNBDUVAKEEMSAAASINWANNWIRLARNMCKUVDRFEFISTRNTSKWLVWMLW = true;
                    break;
                }
            }

            if (DTJAQTQNMGLGLQBHCOUHJFTKRWGQQBSUVRVXJOHHHVPHTKVHNCBAIXAVXWGRMXVLL.Equals(KIJCAUTVIMTKMBTUDAVVCQCKCTQXRNRVIFSKSVFPXIINXCHAQPDTTLQRGWAFETETTWBGGI) || BFTGVRIMLXMPHCJWBVNBDUVAKEEMSAAASINWANNWIRLARNMCKUVDRFEFISTRNTSKWLVWMLW)
            {
                return base.VisitMethodDeclaration(node);
            }
            else
            {
                String LIOQJJUHVQCBVDVHMDINFSUJNXABGQNNXVJTCNSTMLWAKSUHBDITEVRRLEDKJSBFDNCXRBEX= "";
                if (UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS.Instance.GUNBGHMJVWTVMQAPXGCETNOTETLNKAHDQXJVTGGLUHPVFXFNLFIGNKKRGRUK.ContainsKey(DTJAQTQNMGLGLQBHCOUHJFTKRWGQQBSUVRVXJOHHHVPHTKVHNCBAIXAVXWGRMXVLL))
                {
                    LIOQJJUHVQCBVDVHMDINFSUJNXABGQNNXVJTCNSTMLWAKSUHBDITEVRRLEDKJSBFDNCXRBEX = UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS.Instance.GUNBGHMJVWTVMQAPXGCETNOTETLNKAHDQXJVTGGLUHPVFXFNLFIGNKKRGRUK[DTJAQTQNMGLGLQBHCOUHJFTKRWGQQBSUVRVXJOHHHVPHTKVHNCBAIXAVXWGRMXVLL];
                }
                else
                {
                    LIOQJJUHVQCBVDVHMDINFSUJNXABGQNNXVJTCNSTMLWAKSUHBDITEVRRLEDKJSBFDNCXRBEX = UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS.Instance.FSGHFWOAFWCDMFWITPTXVUQFNSIDIISRFCJLKWKSVEXFJRWEIUIWPRUIC(UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS.Instance.GUNBGHMJVWTVMQAPXGCETNOTETLNKAHDQXJVTGGLUHPVFXFNLFIGNKKRGRUK.Count() + 1);
                    UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS.Instance.GUNBGHMJVWTVMQAPXGCETNOTETLNKAHDQXJVTGGLUHPVFXFNLFIGNKKRGRUK[DTJAQTQNMGLGLQBHCOUHJFTKRWGQQBSUVRVXJOHHHVPHTKVHNCBAIXAVXWGRMXVLL] = LIOQJJUHVQCBVDVHMDINFSUJNXABGQNNXVJTCNSTMLWAKSUHBDITEVRRLEDKJSBFDNCXRBEX;
                }
                MethodDeclarationSyntax IQKHWMQKKBRWEPNDJUGLRRCDMBQJQKXBGCXSUPSAEUAPINVEMIRULFRPNHSUUGSXBPP= node.WithIdentifier(Identifier(LIOQJJUHVQCBVDVHMDINFSUJNXABGQNNXVJTCNSTMLWAKSUHBDITEVRRLEDKJSBFDNCXRBEX)).WithLeadingTrivia(node.GetLeadingTrivia()).WithTrailingTrivia(node.GetTrailingTrivia());
                return node.ReplaceNode(node, IQKHWMQKKBRWEPNDJUGLRRCDMBQJQKXBGCXSUPSAEUAPINVEMIRULFRPNHSUUGSXBPP);
            }

        }
    }
}
