using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace CodeObfuscation
{
    class OXNWONKBDPOQUAUXOFUANWIXHNQCTWLUKXDUQMXPFJMFIARLWUWDFRPPOOPAVIGFDSFVUXGBGFT: CSharpSyntaxRewriter
    {
        private string DKCOHUEEWXHORHLFBVWRUCGCOSUOWOVVAWLFMAIERDIFTDMNJSFEHLWADAXNANGICKOSTFRBMRAQ= "override";
        private string SBGLFGFDIQOMXLCLATEDVXDJMSSDBDPNLFGCSMHRICXJUCTICFARNVSSVUWLMBCFBAAREAQMLKSTA= "Main";

        public OXNWONKBDPOQUAUXOFUANWIXHNQCTWLUKXDUQMXPFJMFIARLWUWDFRPPOOPAVIGFDSFVUXGBGFT() { }

        /*public override SyntaxNode VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
        {
            return base.VisitConstructorDeclaration(node);
        }*/

        public override SyntaxNode VisitMethodDeclaration(MethodDeclarationSyntax node)
        {
            String LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD= node.Identifier.ValueText;
            Boolean RNJXJBUCVAOKLEWNUFHARITBBDCMMGCCXSDGMLCAFCDXKGRUSXOFLTGJSIVFXHOPWLLRAPAICGSPET= false;
            foreach (SyntaxToken modifier in node.Modifiers)
            {
                if (modifier.ValueText.Equals(DKCOHUEEWXHORHLFBVWRUCGCOSUOWOVVAWLFMAIERDIFTDMNJSFEHLWADAXNANGICKOSTFRBMRAQ))
                {
                    RNJXJBUCVAOKLEWNUFHARITBBDCMMGCCXSDGMLCAFCDXKGRUSXOFLTGJSIVFXHOPWLLRAPAICGSPET = true;
                    break;
                }
            }

            if (LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD.Equals(SBGLFGFDIQOMXLCLATEDVXDJMSSDBDPNLFGCSMHRICXJUCTICFARNVSSVUWLMBCFBAAREAQMLKSTA) || RNJXJBUCVAOKLEWNUFHARITBBDCMMGCCXSDGMLCAFCDXKGRUSXOFLTGJSIVFXHOPWLLRAPAICGSPET)
            {
                return base.VisitMethodDeclaration(node);
            }
            else
            {
                String PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS= "";
                if (IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX.ContainsKey(LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD))
                {
                    PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS = IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX[LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD];
                }
                else
                {
                    PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS = IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.REEEMFRGJWOQFADSSPEMXUQJWAMNRLFEWRJILXMKVFIKDOBESRBESNUVMSGMQENV(IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX.Count() + 1);
                    IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX[LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD] = PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS;
                }
                MethodDeclarationSyntax SKJWXDHILOOFKAPECLEFEMXSRHQPLMWASPECTBQXOFWAEDUPLUVFDRTFLOEQKQUXQOLSTNJBSE= node.WithIdentifier(Identifier(PSKFRMPUPELRMEOVBWMLBXTATCWFDEAPFWQDTRNBABUHGHDTSFFUDRSQWJKOOJRKDTMOMKBIIKLXCMS)).WithLeadingTrivia(node.GetLeadingTrivia()).WithTrailingTrivia(node.GetTrailingTrivia());
                return node.ReplaceNode(node, SKJWXDHILOOFKAPECLEFEMXSRHQPLMWASPECTBQXOFWAEDUPLUVFDRTFLOEQKQUXQOLSTNJBSE);
            }

        }
    }
}
