using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace CodeObfuscation
{
    class XJASDFEDDQCWQDAUDEWBADMDJSGOTQODVGSDSHVNQDIGPOMNCMCSLHOTUUIJWOHLCWAJ: CSharpSyntaxRewriter
    {
        private string JUCTHJIUTGLSFRLHNTQOQWHVWMOBUUDROCDFKGLBWRANIODFDAWGGJRKNFVSTHAWCSECN= "override";
        private string GUGHOQXVSMIJJWUVVKFJQQEJRGPRBKOJAPUDQWQQSNTQMJJIEBFIXRVOPUOHBFUHWWIRBQ= "Main";

        public XJASDFEDDQCWQDAUDEWBADMDJSGOTQODVGSDSHVNQDIGPOMNCMCSLHOTUUIJWOHLCWAJ() { }

        /*public override SyntaxNode VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
        {
            return base.VisitConstructorDeclaration(node);
        }*/

        public override SyntaxNode VisitMethodDeclaration(MethodDeclarationSyntax node)
        {
            String HBSSRSJXIJJSKXFSMELSRBWQXGRQWVPVDFVHMOHJKNODFWKBGHGQUHIFCCSKBRBKR= node.Identifier.ValueText;
            Boolean FWSMPDUMVIUGNAEGKHSGLTIIPMQLSNAPGLTHNKBRRDXGKSQTCQLAXTFKOJUCLJSHHFACFVQ= false;
            foreach (SyntaxToken modifier in node.Modifiers)
            {
                if (modifier.ValueText.Equals(JUCTHJIUTGLSFRLHNTQOQWHVWMOBUUDROCDFKGLBWRANIODFDAWGGJRKNFVSTHAWCSECN))
                {
                    FWSMPDUMVIUGNAEGKHSGLTIIPMQLSNAPGLTHNKBRRDXGKSQTCQLAXTFKOJUCLJSHHFACFVQ = true;
                    break;
                }
            }

            if (HBSSRSJXIJJSKXFSMELSRBWQXGRQWVPVDFVHMOHJKNODFWKBGHGQUHIFCCSKBRBKR.Equals(GUGHOQXVSMIJJWUVVKFJQQEJRGPRBKOJAPUDQWQQSNTQMJJIEBFIXRVOPUOHBFUHWWIRBQ) || FWSMPDUMVIUGNAEGKHSGLTIIPMQLSNAPGLTHNKBRRDXGKSQTCQLAXTFKOJUCLJSHHFACFVQ)
            {
                return base.VisitMethodDeclaration(node);
            }
            else
            {
                String AFANHTCWVTVIBBAQLFJRENXGIJQWFROOFXLSWGVOLLXHOAQFHMNUUEMKGSFWDDQDEGDBOFRF= "";
                if (MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX.Instance.HVIPMSGNAAKLKRDVSPOFDJECEXDXOOVMCUBMJQARAGWJVJGHALOXHFMWRGKN.ContainsKey(HBSSRSJXIJJSKXFSMELSRBWQXGRQWVPVDFVHMOHJKNODFWKBGHGQUHIFCCSKBRBKR))
                {
                    AFANHTCWVTVIBBAQLFJRENXGIJQWFROOFXLSWGVOLLXHOAQFHMNUUEMKGSFWDDQDEGDBOFRF = MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX.Instance.HVIPMSGNAAKLKRDVSPOFDJECEXDXOOVMCUBMJQARAGWJVJGHALOXHFMWRGKN[HBSSRSJXIJJSKXFSMELSRBWQXGRQWVPVDFVHMOHJKNODFWKBGHGQUHIFCCSKBRBKR];
                }
                else
                {
                    AFANHTCWVTVIBBAQLFJRENXGIJQWFROOFXLSWGVOLLXHOAQFHMNUUEMKGSFWDDQDEGDBOFRF = MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX.Instance.VTXUONHIQXSVIHGLFTVQJGIQKWWOEOWOJPVUEMFXFSFDDDSCWXDNWQOPK(MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX.Instance.HVIPMSGNAAKLKRDVSPOFDJECEXDXOOVMCUBMJQARAGWJVJGHALOXHFMWRGKN.Count() + 1);
                    MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX.Instance.HVIPMSGNAAKLKRDVSPOFDJECEXDXOOVMCUBMJQARAGWJVJGHALOXHFMWRGKN[HBSSRSJXIJJSKXFSMELSRBWQXGRQWVPVDFVHMOHJKNODFWKBGHGQUHIFCCSKBRBKR] = AFANHTCWVTVIBBAQLFJRENXGIJQWFROOFXLSWGVOLLXHOAQFHMNUUEMKGSFWDDQDEGDBOFRF;
                }
                MethodDeclarationSyntax GJRSOQBMFEGVOVVRCFWJCHPENVNPGFSWGPMVWWARFWONGURMSCATVGMXRNERCJGXKIO= node.WithIdentifier(Identifier(AFANHTCWVTVIBBAQLFJRENXGIJQWFROOFXLSWGVOLLXHOAQFHMNUUEMKGSFWDDQDEGDBOFRF)).WithLeadingTrivia(node.GetLeadingTrivia()).WithTrailingTrivia(node.GetTrailingTrivia());
                return node.ReplaceNode(node, GJRSOQBMFEGVOVVRCFWJCHPENVNPGFSWGPMVWWARFWONGURMSCATVGMXRNERCJGXKIO);
            }

        }
    }
}
