using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace CodeObfuscation
{
    class JQNPSHAHVQLIXGINNVSBTFEUKHSHMESXMANNGWOVWRFBWIBCWEUKJWOELRELMRSRVMTW: CSharpSyntaxRewriter
    {
        public JQNPSHAHVQLIXGINNVSBTFEUKHSHMESXMANNGWOVWRFBWIBCWEUKJWOELRELMRSRVMTW() { }
        public override SyntaxNode Visit(SyntaxNode node)
        {
            if (node != null)
            {
                var RSHPGUCCXDWCGQJIIINOJJBMRDJFWMDKMCIDUEDMUMEITCFTIKJNWFNHQSVDLUDLXLNEH= node.DescendantTokens();
                if (node is FieldDeclarationSyntax)
                {
                    var FMDEBSVFRRPVOVMDNMHMBKCHXBXIQIHMALCVFJUKPCWAGFUXOHKXGPGTJTEATMMJKCUCTO= (FieldDeclarationSyntax)node;
                    if (FMDEBSVFRRPVOVMDNMHMBKCHXBXIQIHMALCVFJUKPCWAGFUXOHKXGPGTJTEATMMJKCUCTO.Declaration.Type is IdentifierNameSyntax)
                    {
                        var VEPUUXLBAREASIWHGJFHLKEUPDNNODJSEAKFIJSHHISKTTSDLCULVLCLXSFRJWLVIKTRWQX= (IdentifierNameSyntax)FMDEBSVFRRPVOVMDNMHMBKCHXBXIQIHMALCVFJUKPCWAGFUXOHKXGPGTJTEATMMJKCUCTO.Declaration.Type;
                        var UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE= VEPUUXLBAREASIWHGJFHLKEUPDNNODJSEAKFIJSHHISKTTSDLCULVLCLXSFRJWLVIKTRWQX.Identifier.ValueText;
                        if (BLSVUOJMAXPVAKJUFLGRGCNPOIPECQSKJLMCXPFCDMBVBOBFOLUPNQXWVCHL.Instance.TUHINNPNAKHURWVXAPNIIBSPSDTAHSJBDEVDENQUPXUWPXMLTGGOJGJRCQOKSPFGB.ContainsKey(UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE))
                        {
                            if (!BLSVUOJMAXPVAKJUFLGRGCNPOIPECQSKJLMCXPFCDMBVBOBFOLUPNQXWVCHL.Instance.TUHINNPNAKHURWVXAPNIIBSPSDTAHSJBDEVDENQUPXUWPXMLTGGOJGJRCQOKSPFGB[UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE].Equals(JLMSVBBREMWJRJPOCWVUUDBMDIJOWSUWQIEMAEQDUXETQXWDOXVCAHWGJAOMPLSKPXRIECNVFSXUWFTDKFAWURVJJWDAN.En_Priority.CLASS))
                            {
                                return node;
                            }
                        }
                    }
                }

                if (node is ParameterSyntax)
                {
                    var WDXTTRWLVHOTTDFIRHFXVRCNCLWSOPGJQXWULOVUCDIKCTBFXWOATVHEAKQHSDUGBEDUFJUCJ= (ParameterSyntax)node;
                    if (WDXTTRWLVHOTTDFIRHFXVRCNCLWSOPGJQXWULOVUCDIKCTBFXWOATVHEAKQHSDUGBEDUFJUCJ.Type is IdentifierNameSyntax)
                    {
                        var VEPUUXLBAREASIWHGJFHLKEUPDNNODJSEAKFIJSHHISKTTSDLCULVLCLXSFRJWLVIKTRWQX= (IdentifierNameSyntax)WDXTTRWLVHOTTDFIRHFXVRCNCLWSOPGJQXWULOVUCDIKCTBFXWOATVHEAKQHSDUGBEDUFJUCJ.Type;
                        var UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE= VEPUUXLBAREASIWHGJFHLKEUPDNNODJSEAKFIJSHHISKTTSDLCULVLCLXSFRJWLVIKTRWQX.Identifier.ValueText;
                        if (BLSVUOJMAXPVAKJUFLGRGCNPOIPECQSKJLMCXPFCDMBVBOBFOLUPNQXWVCHL.Instance.TUHINNPNAKHURWVXAPNIIBSPSDTAHSJBDEVDENQUPXUWPXMLTGGOJGJRCQOKSPFGB.ContainsKey(UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE))
                        {
                            if (!BLSVUOJMAXPVAKJUFLGRGCNPOIPECQSKJLMCXPFCDMBVBOBFOLUPNQXWVCHL.Instance.TUHINNPNAKHURWVXAPNIIBSPSDTAHSJBDEVDENQUPXUWPXMLTGGOJGJRCQOKSPFGB[UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE].Equals(JLMSVBBREMWJRJPOCWVUUDBMDIJOWSUWQIEMAEQDUXETQXWDOXVCAHWGJAOMPLSKPXRIECNVFSXUWFTDKFAWURVJJWDAN.En_Priority.CLASS))
                            {
                                return node;
                            }
                        }
                    }
                }

                if (RSHPGUCCXDWCGQJIIINOJJBMRDJFWMDKMCIDUEDMUMEITCFTIKJNWFNHQSVDLUDLXLNEH.Count() > 0)
                {
                    foreach (SyntaxToken token in RSHPGUCCXDWCGQJIIINOJJBMRDJFWMDKMCIDUEDMUMEITCFTIKJNWFNHQSVDLUDLXLNEH)
                    {
                        //Console.WriteLine(token.ValueText + " *** " + token.IsKeyword());
                        var UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE= token.ValueText;
                        if (BLSVUOJMAXPVAKJUFLGRGCNPOIPECQSKJLMCXPFCDMBVBOBFOLUPNQXWVCHL.Instance.VANRFCWHOSAVXWTICCBHPQOVLVUXQUXDNPIFQNBOASWQAMVFKHMVJWUFJQFHFWPR.ContainsKey(UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE))
                        {
                            if (node is IdentifierNameSyntax)
                            {
                                var JVRIQLHKRTQAGNTQRTAWOCWHBIVQFXNBLOKANTIXIVBIDFTPHDMOUETHWKHHNPESFPNPCTCVKB= (IdentifierNameSyntax)node;
                                IdentifierNameSyntax NRAODUNGICLXFHTDBDMBJRQHCMQEMMAODTOBGIHLRHGCGGKGTWRXIJPTARMOEJRUBUUKQRVRTBH= JVRIQLHKRTQAGNTQRTAWOCWHBIVQFXNBLOKANTIXIVBIDFTPHDMOUETHWKHHNPESFPNPCTCVKB.WithIdentifier(Identifier(BLSVUOJMAXPVAKJUFLGRGCNPOIPECQSKJLMCXPFCDMBVBOBFOLUPNQXWVCHL.Instance.VANRFCWHOSAVXWTICCBHPQOVLVUXQUXDNPIFQNBOASWQAMVFKHMVJWUFJQFHFWPR[UPVXDPSAUJKBLHVUQVXFNEBVIVVBJXAFTDXTXMXUFSJHXVXOLNDUXLJQOAPGRQPVJEGIHBUE])).WithLeadingTrivia(JVRIQLHKRTQAGNTQRTAWOCWHBIVQFXNBLOKANTIXIVBIDFTPHDMOUETHWKHHNPESFPNPCTCVKB.GetLeadingTrivia()).WithTrailingTrivia(JVRIQLHKRTQAGNTQRTAWOCWHBIVQFXNBLOKANTIXIVBIDFTPHDMOUETHWKHHNPESFPNPCTCVKB.GetTrailingTrivia());
                                return node.ReplaceNode(JVRIQLHKRTQAGNTQRTAWOCWHBIVQFXNBLOKANTIXIVBIDFTPHDMOUETHWKHHNPESFPNPCTCVKB, NRAODUNGICLXFHTDBDMBJRQHCMQEMMAODTOBGIHLRHGCGGKGTWRXIJPTARMOEJRUBUUKQRVRTBH);
                            }

                        }
                    }
                }

            }

            return base.Visit(node);
        }
    }
}
