using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace CodeObfuscation
{
    class JGTTCXVXIRQKIXLUXARCAVDLRVVEUFPOEERSUBJXEKQDUHOPEFXJWIKMCHBFCQDDCCFDGQ: CSharpSyntaxRewriter
    {
        public JGTTCXVXIRQKIXLUXARCAVDLRVVEUFPOEERSUBJXEKQDUHOPEFXJWIKMCHBFCQDDCCFDGQ() { }
        public override SyntaxNode Visit(SyntaxNode node)
        {
            if (node != null)
            {
                var XVPSVOEAOJGFAOGGQUSEPNAEULGNASBKJLGBREKTHCQPWUQNUUKJJBAKVKVKIPXUHUUMHEM= node.DescendantTokens();

                if (XVPSVOEAOJGFAOGGQUSEPNAEULGNASBKJLGBREKTHCQPWUQNUUKJJBAKVKVKIPXUHUUMHEM.Count() > 0)
                {
                    foreach (SyntaxToken token in XVPSVOEAOJGFAOGGQUSEPNAEULGNASBKJLGBREKTHCQPWUQNUUKJJBAKVKVKIPXUHUUMHEM)
                    {
                        //Console.WriteLine(token.ValueText + " *** " + token.IsKeyword());
                        string LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD= token.ValueText;
                        if (IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX.ContainsKey(LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD))
                        {
                            if (node is IdentifierNameSyntax)
                            {
                                IdentifierNameSyntax XGPBKJUQIIQHLCTQDSQAWAOMCVAFWWBAEJBDIDRWONCOISMMOIRPXNEXQDWNJPSJGPDBAQIXA= (IdentifierNameSyntax)node;
                                IdentifierNameSyntax SKJWXDHILOOFKAPECLEFEMXSRHQPLMWASPECTBQXOFWAEDUPLUVFDRTFLOEQKQUXQOLSTNJBSE= XGPBKJUQIIQHLCTQDSQAWAOMCVAFWWBAEJBDIDRWONCOISMMOIRPXNEXQDWNJPSJGPDBAQIXA.WithIdentifier(Identifier(IOUSNTGIIFIJTWFLPASQTDPJWQUDMOBEFHRLEGCEANCMPEBPPMRJSHGFWLTUXCU.Instance.BKKQSUFFHQNFNHCLCLSLXFFGEGFDNPIBFLPDMDFLCBIBDQMERLITUFVUEEMMOCPQHLX[LJWVNUIFATQQEIQBHKUEGHALPCUHCAEGQIWALELNMFUPPWSLPSNBKXFEIKFKXACXOKAUJPOD])).WithLeadingTrivia(XGPBKJUQIIQHLCTQDSQAWAOMCVAFWWBAEJBDIDRWONCOISMMOIRPXNEXQDWNJPSJGPDBAQIXA.GetLeadingTrivia()).WithTrailingTrivia(XGPBKJUQIIQHLCTQDSQAWAOMCVAFWWBAEJBDIDRWONCOISMMOIRPXNEXQDWNJPSJGPDBAQIXA.GetTrailingTrivia());
                                return node.ReplaceNode(XGPBKJUQIIQHLCTQDSQAWAOMCVAFWWBAEJBDIDRWONCOISMMOIRPXNEXQDWNJPSJGPDBAQIXA, SKJWXDHILOOFKAPECLEFEMXSRHQPLMWASPECTBQXOFWAEDUPLUVFDRTFLOEQKQUXQOLSTNJBSE);
                            }

                        }
                    }
                }

            }

            return base.Visit(node);
        }
    }
}
