using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Symbols;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.IO;

namespace CodeObfuscation
{
    class TBTBO    {
        static void Main(string[] args)
        {
            NELTLHRD AWAEKW= new NELTLHRD();
            
            GBSKQCQWCVQQNAQLHSCJDJMOMMGCGLHPCSIXWVSPGCQWDCDUKCVMGGQUNEWDTOPONBOTQRNJXLCBQ.En_Priority[] ONXLAIP= { GBSKQCQWCVQQNAQLHSCJDJMOMMGCGLHPCSIXWVSPGCQWDCDUKCVMGGQUNEWDTOPONBOTQRNJXLCBQ.En_Priority.CLASS, GBSKQCQWCVQQNAQLHSCJDJMOMMGCGLHPCSIXWVSPGCQWDCDUKCVMGGQUNEWDTOPONBOTQRNJXLCBQ.En_Priority.CONSTRUCTOR, GBSKQCQWCVQQNAQLHSCJDJMOMMGCGLHPCSIXWVSPGCQWDCDUKCVMGGQUNEWDTOPONBOTQRNJXLCBQ.En_Priority.METHOD, GBSKQCQWCVQQNAQLHSCJDJMOMMGCGLHPCSIXWVSPGCQWDCDUKCVMGGQUNEWDTOPONBOTQRNJXLCBQ.En_Priority.VARIABLE, GBSKQCQWCVQQNAQLHSCJDJMOMMGCGLHPCSIXWVSPGCQWDCDUKCVMGGQUNEWDTOPONBOTQRNJXLCBQ.En_Priority.OCCURENCE };
            AWAEKW.CSDACULKM(ONXLAIP);
        }
    }
}
