using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Symbols;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.IO;

namespace CodeObfuscation
{
    class OKVVI    {
        static void Main(string[] args)
        {
            BITFNJFX URDOAJ= new BITFNJFX();
            
            OBGNINJHRGAXUHQPWBSQJHJVFILETRQNGRNSOWSWMHMWKCQXHENBATFGPJIACFMXNKQDRVAXHTEBT.En_Priority[] PRGOSGO= { OBGNINJHRGAXUHQPWBSQJHJVFILETRQNGRNSOWSWMHMWKCQXHENBATFGPJIACFMXNKQDRVAXHTEBT.En_Priority.CLASS, OBGNINJHRGAXUHQPWBSQJHJVFILETRQNGRNSOWSWMHMWKCQXHENBATFGPJIACFMXNKQDRVAXHTEBT.En_Priority.CONSTRUCTOR, OBGNINJHRGAXUHQPWBSQJHJVFILETRQNGRNSOWSWMHMWKCQXHENBATFGPJIACFMXNKQDRVAXHTEBT.En_Priority.METHOD, OBGNINJHRGAXUHQPWBSQJHJVFILETRQNGRNSOWSWMHMWKCQXHENBATFGPJIACFMXNKQDRVAXHTEBT.En_Priority.VARIABLE, OBGNINJHRGAXUHQPWBSQJHJVFILETRQNGRNSOWSWMHMWKCQXHENBATFGPJIACFMXNKQDRVAXHTEBT.En_Priority.OCCURENCE/*, Priority.En_Priority.TYPE_INFERENCE */};
            URDOAJ.WVUWXHTKD(PRGOSGO);
        }
    }
}
