using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeObfuscation
{
    class CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB    {
        private static readonly CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB NWBPLPCXQDRTWQLKSVXUMWOKXJBWROIQXSICXGXEEJPSFLRIXWOSXHSPIOPC= new CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB();
        private Random NEFCTAUEIJKMWTPCGTFMQRWSXORPXQRJOUOAENXEPMAOMBTEPPJMIDKUGKCEH= new Random();
        public Dictionary<string, string> EFPPBVBEPWQUAUDRHGWSMXHHEALKSSSLSUKHIWKDSAARQQHGGDWDEKTEVILAKO= new Dictionary<string, string>();
        private CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB() { }
        public static CRMJFJNCCELINXAQEUMIJBVLJKAIGORNTTKWABLMHSMLTAOUKXCIGRQATB Instance
        {
            get
            {
                return NWBPLPCXQDRTWQLKSVXUMWOKXJBWROIQXSICXGXEEJPSFLRIXWOSXHSPIOPC;
            }
        }

        public string ATIFULKWNSMBPDJXAPMKQITEVGMJGBCKCXAQDBWBAVKUHIIWWHQBLJJPXEH(int length)
        {
            const string JVEEBDKTIJTSALXNOMREDPUOHIBFJALKRDODNMODULSMIJJHFHRWHGKSAOVRCEJ= "ABCDEFGHIJKLMNOPQRSTUVWX";
            string IWJBVVUACVNHQVHFVWSABGMCLQUCXOVBQBJOWIMKJHPBRWSURIXSHEHBKGOEARBL= new string(Enumerable.Repeat(JVEEBDKTIJTSALXNOMREDPUOHIBFJALKRDODNMODULSMIJJHFHRWHGKSAOVRCEJ, length + 4)
              .Select(s => s[NEFCTAUEIJKMWTPCGTFMQRWSXORPXQRJOUOAENXEPMAOMBTEPPJMIDKUGKCEH.Next(s.Length)]).ToArray());
            foreach(string value in EFPPBVBEPWQUAUDRHGWSMXHHEALKSSSLSUKHIWKDSAARQQHGGDWDEKTEVILAKO.Values)
            {
                if (value.Equals(IWJBVVUACVNHQVHFVWSABGMCLQUCXOVBQBJOWIMKJHPBRWSURIXSHEHBKGOEARBL))
                {
                    return ATIFULKWNSMBPDJXAPMKQITEVGMJGBCKCXAQDBWBAVKUHIIWWHQBLJJPXEH(length);
                }
            }
            return IWJBVVUACVNHQVHFVWSABGMCLQUCXOVBQBJOWIMKJHPBRWSURIXSHEHBKGOEARBL;
        }
    }
}
