using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeObfuscation
{
    class UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS    {
        private static readonly UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS BRLNKQUEIWJUKWVEACRVKTUUETLATBLFAJIEXFKMCBATMIVWKRPPDLPGVP= new UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS();
        private Random JOEUIHKETBOQFTPFSJSAHTWNNBKUCNRBHIUUHGQRJIMTIRMUAVRGLUHNQPG= new Random();
        public Dictionary<string, string> GUNBGHMJVWTVMQAPXGCETNOTETLNKAHDQXJVTGGLUHPVFXFNLFIGNKKRGRUK= new Dictionary<string, string>();
        private UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS() { }
        public static UHOARLRBORGHCJUEBBIMLCBURKFTKNMIFWUOGRFQRLEFDMVKKGFDNLRS Instance
        {
            get
            {
                return BRLNKQUEIWJUKWVEACRVKTUUETLATBLFAJIEXFKMCBATMIVWKRPPDLPGVP;
            }
        }

        public string FSGHFWOAFWCDMFWITPTXVUQFNSIDIISRFCJLKWKSVEXFJRWEIUIWPRUIC(int length)
        {
            const string UWXUPPFNHDUQAPIMWQOEOVCFPAOFMQOBKTOVISGOSQGHJQFWBWSNDPUXTSEOA= "ABCDEFGHIJKLMNOPQRSTUVWX";
            string AAOMSFEAKDDKAKWPTUXSQDNWBWSXPCNOPNRPPSOKBWPSODCEVHAWFTIULQLTKE= new string(Enumerable.Repeat(UWXUPPFNHDUQAPIMWQOEOVCFPAOFMQOBKTOVISGOSQGHJQFWBWSNDPUXTSEOA, length + 4)
              .Select(s => s[JOEUIHKETBOQFTPFSJSAHTWNNBKUCNRBHIUUHGQRJIMTIRMUAVRGLUHNQPG.Next(s.Length)]).ToArray());
            foreach(string value in GUNBGHMJVWTVMQAPXGCETNOTETLNKAHDQXJVTGGLUHPVFXFNLFIGNKKRGRUK.Values)
            {
                if (value.Equals(AAOMSFEAKDDKAKWPTUXSQDNWBWSXPCNOPNRPPSOKBWPSODCEVHAWFTIULQLTKE))
                {
                    return FSGHFWOAFWCDMFWITPTXVUQFNSIDIISRFCJLKWKSVEXFJRWEIUIWPRUIC(length);
                }
            }
            return AAOMSFEAKDDKAKWPTUXSQDNWBWSXPCNOPNRPPSOKBWPSODCEVHAWFTIULQLTKE;
        }
    }
}
