using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeObfuscation
{
    class MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX    {
        private static readonly MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX GJQPRECBEMRKJHQNVKPAFMHDUQEKIPQAGJVCNIMNDCXOAQMQKXAFWOESCM= new MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX();
        private Random SBXPQMTQDXJOANVBVDNQCDDMXIPLBPFDAANKOLJKSHMMGUWKIVQBEJJPVLP= new Random();
        public Dictionary<string, string> HVIPMSGNAAKLKRDVSPOFDJECEXDXOOVMCUBMJQARAGWJVJGHALOXHFMWRGKN= new Dictionary<string, string>();
        private MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX() { }
        public static MBGMJQWCXPFDPXCVOOOJFMELNMBISPXGJROTPDJTMNCWCVBDKEKIITIX Instance
        {
            get
            {
                return GJQPRECBEMRKJHQNVKPAFMHDUQEKIPQAGJVCNIMNDCXOAQMQKXAFWOESCM;
            }
        }

        public string VTXUONHIQXSVIHGLFTVQJGIQKWWOEOWOJPVUEMFXFSFDDDSCWXDNWQOPK(int length)
        {
            const string PHXJDVIOPOMBPVFULSFTQTWCXVFVIDTDGLCRHNGXAQQJXNIJAPLWAPUTIUJFP= "ABCDEFGHIJKLMNOPQRSTUVWX";
            string LFLTITDSMNVLFSXDMDKMUUQQUDOOGIKDBHMKEOPRFPMBNLSUUQUQWQTONTWEEN= new string(Enumerable.Repeat(PHXJDVIOPOMBPVFULSFTQTWCXVFVIDTDGLCRHNGXAQQJXNIJAPLWAPUTIUJFP, length + 4)
              .Select(s => s[SBXPQMTQDXJOANVBVDNQCDDMXIPLBPFDAANKOLJKSHMMGUWKIVQBEJJPVLP.Next(s.Length)]).ToArray());
            foreach(string value in HVIPMSGNAAKLKRDVSPOFDJECEXDXOOVMCUBMJQARAGWJVJGHALOXHFMWRGKN.Values)
            {
                if (value.Equals(LFLTITDSMNVLFSXDMDKMUUQQUDOOGIKDBHMKEOPRFPMBNLSUUQUQWQTONTWEEN))
                {
                    return VTXUONHIQXSVIHGLFTVQJGIQKWWOEOWOJPVUEMFXFSFDDDSCWXDNWQOPK(length);
                }
            }
            return LFLTITDSMNVLFSXDMDKMUUQQUDOOGIKDBHMKEOPRFPMBNLSUUQUQWQTONTWEEN;
        }
    }
}
